version: "3.8"

services:
  frontend-react:
    container_name: frontend-react
    image: react:1.0.0
    build: "./frontend"
    env_file:
      - ./.env
    ports:
      - 3000:3000
    depends_on:
      - backend-springboot
  backend-springboot:
    container_name: backend-springboot
    image: springboot:1.0.0
    build: "./backend"
    env_file:
      - ./.env
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://${POSTGRES_HOSTNAME}:${POSTGRES_PORT}/${POSTGRES_DBNAME}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - database-postgres
  database-postgres:
    container_name: database-postgres
    image: postgres:12
    env_file:
      - ./.env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DBNAME}